//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP {
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Helpers;
using System.Web.Security;
using System.Web.UI;
using System.Web.WebPages;
using System.Web.WebPages.Html;

public class _Page_Index_cshtml : System.Web.WebPages.WebPage {
private static object @__o;
#line hidden
public _Page_Index_cshtml() {
}
protected System.Web.HttpApplication ApplicationInstance {
get {
return ((System.Web.HttpApplication)(Context.ApplicationInstance));
}
}
public override void Execute() {

#line 1 "C:\Users\Tuan\AppData\Local\Temp\38EF60BCFCCEB60BDA800F28F94C5A9468FF\2\Trave\Views\Home\Index.cshtml"
__o = model;


#line default
#line hidden

#line 2 "C:\Users\Tuan\AppData\Local\Temp\38EF60BCFCCEB60BDA800F28F94C5A9468FF\2\Trave\Views\Home\Index.cshtml"
  
    ViewBag.Title = "Travela - Dream Destinations, Unforgettable Experiences";


#line default
#line hidden

#line 3 "C:\Users\Tuan\AppData\Local\Temp\38EF60BCFCCEB60BDA800F28F94C5A9468FF\2\Trave\Views\Home\Index.cshtml"
                                                                                                           __o = Url.Action("tour","home");


#line default
#line hidden

#line 4 "C:\Users\Tuan\AppData\Local\Temp\38EF60BCFCCEB60BDA800F28F94C5A9468FF\2\Trave\Views\Home\Index.cshtml"
                                                                                                           __o = Url.Action("tour","home");


#line default
#line hidden

#line 5 "C:\Users\Tuan\AppData\Local\Temp\38EF60BCFCCEB60BDA800F28F94C5A9468FF\2\Trave\Views\Home\Index.cshtml"
                                                                                                           __o = Url.Action("tour","home");


#line default
#line hidden

#line 6 "C:\Users\Tuan\AppData\Local\Temp\38EF60BCFCCEB60BDA800F28F94C5A9468FF\2\Trave\Views\Home\Index.cshtml"
                foreach (var item in Model.DiaDiems.Take(4))
                {
                    

#line default
#line hidden

#line 7 "C:\Users\Tuan\AppData\Local\Temp\38EF60BCFCCEB60BDA800F28F94C5A9468FF\2\Trave\Views\Home\Index.cshtml"
                                   __o = item.MaDD;


#line default
#line hidden

#line 8 "C:\Users\Tuan\AppData\Local\Temp\38EF60BCFCCEB60BDA800F28F94C5A9468FF\2\Trave\Views\Home\Index.cshtml"
                                          __o = item.MaDD;


#line default
#line hidden

#line 9 "C:\Users\Tuan\AppData\Local\Temp\38EF60BCFCCEB60BDA800F28F94C5A9468FF\2\Trave\Views\Home\Index.cshtml"
                                                  __o = item.MaDD;


#line default
#line hidden

#line 10 "C:\Users\Tuan\AppData\Local\Temp\38EF60BCFCCEB60BDA800F28F94C5A9468FF\2\Trave\Views\Home\Index.cshtml"
                       __o = item.QuocGia;


#line default
#line hidden

#line 11 "C:\Users\Tuan\AppData\Local\Temp\38EF60BCFCCEB60BDA800F28F94C5A9468FF\2\Trave\Views\Home\Index.cshtml"
                         
                }

#line default
#line hidden

#line 12 "C:\Users\Tuan\AppData\Local\Temp\38EF60BCFCCEB60BDA800F28F94C5A9468FF\2\Trave\Views\Home\Index.cshtml"
                if (Model.DiaDiems.Count() > 4)
                {
                    

#line default
#line hidden

#line 13 "C:\Users\Tuan\AppData\Local\Temp\38EF60BCFCCEB60BDA800F28F94C5A9468FF\2\Trave\Views\Home\Index.cshtml"
                                    foreach (var item in Model.DiaDiems.Skip(4))
                                    {
                                        

#line default
#line hidden

#line 14 "C:\Users\Tuan\AppData\Local\Temp\38EF60BCFCCEB60BDA800F28F94C5A9468FF\2\Trave\Views\Home\Index.cshtml"
                                                       __o = item.MaDD;


#line default
#line hidden

#line 15 "C:\Users\Tuan\AppData\Local\Temp\38EF60BCFCCEB60BDA800F28F94C5A9468FF\2\Trave\Views\Home\Index.cshtml"
                                                              __o = item.MaDD;


#line default
#line hidden

#line 16 "C:\Users\Tuan\AppData\Local\Temp\38EF60BCFCCEB60BDA800F28F94C5A9468FF\2\Trave\Views\Home\Index.cshtml"
                                                                      __o = item.MaDD;


#line default
#line hidden

#line 17 "C:\Users\Tuan\AppData\Local\Temp\38EF60BCFCCEB60BDA800F28F94C5A9468FF\2\Trave\Views\Home\Index.cshtml"
                                           __o = item.QuocGia;


#line default
#line hidden

#line 18 "C:\Users\Tuan\AppData\Local\Temp\38EF60BCFCCEB60BDA800F28F94C5A9468FF\2\Trave\Views\Home\Index.cshtml"
                                              
                                    }

#line default
#line hidden

#line 19 "C:\Users\Tuan\AppData\Local\Temp\38EF60BCFCCEB60BDA800F28F94C5A9468FF\2\Trave\Views\Home\Index.cshtml"
                         
                }

#line default
#line hidden

#line 20 "C:\Users\Tuan\AppData\Local\Temp\38EF60BCFCCEB60BDA800F28F94C5A9468FF\2\Trave\Views\Home\Index.cshtml"
                        foreach (var item in Model.DiaDiems.Take(6))
                        {
                            

#line default
#line hidden

#line 21 "C:\Users\Tuan\AppData\Local\Temp\38EF60BCFCCEB60BDA800F28F94C5A9468FF\2\Trave\Views\Home\Index.cshtml"
                                                                                                     __o = Url.Content("~/img/Destination/"+item.HinhAnh);


#line default
#line hidden

#line 22 "C:\Users\Tuan\AppData\Local\Temp\38EF60BCFCCEB60BDA800F28F94C5A9468FF\2\Trave\Views\Home\Index.cshtml"
                                                                                                                                                           __o = item.ThanhPho;


#line default
#line hidden

#line 23 "C:\Users\Tuan\AppData\Local\Temp\38EF60BCFCCEB60BDA800F28F94C5A9468FF\2\Trave\Views\Home\Index.cshtml"
                                                                    __o = item.ThanhPho;


#line default
#line hidden

#line 24 "C:\Users\Tuan\AppData\Local\Temp\38EF60BCFCCEB60BDA800F28F94C5A9468FF\2\Trave\Views\Home\Index.cshtml"
                                            __o = Url.Content("~/img/Destination/"+item.HinhAnh);


#line default
#line hidden

#line 25 "C:\Users\Tuan\AppData\Local\Temp\38EF60BCFCCEB60BDA800F28F94C5A9468FF\2\Trave\Views\Home\Index.cshtml"
                                  
                        }

#line default
#line hidden

#line 26 "C:\Users\Tuan\AppData\Local\Temp\38EF60BCFCCEB60BDA800F28F94C5A9468FF\2\Trave\Views\Home\Index.cshtml"
                foreach (var item in Model.DiaDiems)
                {
                    

#line default
#line hidden

#line 27 "C:\Users\Tuan\AppData\Local\Temp\38EF60BCFCCEB60BDA800F28F94C5A9468FF\2\Trave\Views\Home\Index.cshtml"
                                     __o = item.MaDD;


#line default
#line hidden

#line 28 "C:\Users\Tuan\AppData\Local\Temp\38EF60BCFCCEB60BDA800F28F94C5A9468FF\2\Trave\Views\Home\Index.cshtml"
                                              __o = item.MaDD;


#line default
#line hidden

#line 29 "C:\Users\Tuan\AppData\Local\Temp\38EF60BCFCCEB60BDA800F28F94C5A9468FF\2\Trave\Views\Home\Index.cshtml"
                                            __o = item.QuocGia;


#line default
#line hidden

#line 30 "C:\Users\Tuan\AppData\Local\Temp\38EF60BCFCCEB60BDA800F28F94C5A9468FF\2\Trave\Views\Home\Index.cshtml"
                          
                }

#line default
#line hidden
}
}
}
