//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Trave.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Booking
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Booking()
        {
            this.DanhGias = new HashSet<DanhGia>();
            this.TinhTrangTours = new HashSet<TinhTrangTour>();
        }
    
        public int MaBooking { get; set; }
        public int MaKH { get; set; }
        public string MaTour { get; set; }
        public Nullable<System.DateTime> NgayDat { get; set; }
        public System.DateTime NgayDi { get; set; }
        public int SoNguoi { get; set; }
        public Nullable<decimal> TongGia { get; set; }
        public string TrangThai { get; set; }
        public string ghichu { get; set; }
    
        public virtual KhachHang KhachHang { get; set; }
        public virtual Tour Tour { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DanhGia> DanhGias { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TinhTrangTour> TinhTrangTours { get; set; }
    }
}
