//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Trave.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Booking
    {
        public int BookingID { get; set; }
        public string MaTour { get; set; }
        public string HoTen { get; set; }
        public string Email { get; set; }
        public string SoDienThoai { get; set; }
        public int SoNguoi { get; set; }
        public System.DateTime NgayDi { get; set; }
        public decimal TongTien { get; set; }
        public string GhiChu { get; set; }
        public string PaymentMethod { get; set; }
        public Nullable<System.DateTime> NgayDat { get; set; }
        public string PhuongTien { get; set; }
    
        public virtual Tour Tour { get; set; }
    }
}
