//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Trave.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChatMessage
    {
        public int Id { get; set; }
        public string SenderId { get; set; }
        public string ReceiverId { get; set; }
        public string Message { get; set; }
        public Nullable<System.DateTime> Timestamp { get; set; }
        public Nullable<bool> IsRead { get; set; }
        public Nullable<int> MaKH { get; set; }
    
        public virtual KhachHang KhachHang { get; set; }
    }
}
