//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Trave.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DatVe
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DatVe()
        {
            this.HoaDons = new HashSet<HoaDon>();
            this.LichSuDats = new HashSet<LichSuDat>();
            this.ThanhToans = new HashSet<ThanhToan>();
        }
    
        public string MaTour { get; set; }
        public string MaKH { get; set; }
        public System.DateTime NgayDat { get; set; }
        public System.DateTime NgayDi { get; set; }
        public int SoLuongNguoi { get; set; }
        public double TongTien { get; set; }
        public string MaDatVe { get; set; }
        public string MaKM { get; set; }
    
        public virtual KhuyenMai KhuyenMai { get; set; }
        public virtual Tour Tour { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HoaDon> HoaDons { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LichSuDat> LichSuDats { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ThanhToan> ThanhToans { get; set; }
        public virtual Tour Tour1 { get; set; }
    }
}
