//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Trave.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class guide
    {
        public int maguide { get; set; }
        public string anhguide { get; set; }
        public string tenguide { get; set; }
        public string quoctich { get; set; }
        public Nullable<int> tuoi { get; set; }
    }
}
