//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Trave.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HoaDon
    {
        public double TongTien { get; set; }
        public string TrangThai { get; set; }
        public string PhuongThucTT { get; set; }
        public System.DateTime NgayLap { get; set; }
        public string MaDatVe { get; set; }
        public string MaHD { get; set; }
        public string GhiChu { get; set; }
        public string MaNV { get; set; }
    
        public virtual DatVe DatVe { get; set; }
        public virtual NhanVien NhanVien { get; set; }
    }
}
