//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Trave.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class KhuyenMai
    {
        public string DieuKien { get; set; }
        public double SoTienGiam { get; set; }
        public string MoTa { get; set; }
        public string TenKM { get; set; }
        public string MaKM { get; set; }
        public string TrangThai { get; set; }
    }
}
