//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Trave.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TinhTrangTour
    {
        public int Matinhtrang { get; set; }
        public string Tentinhtrang { get; set; }
        public Nullable<int> MaBooking { get; set; }
        public Nullable<int> TrangThai { get; set; }
    
        public virtual Booking Booking { get; set; }
    }
}
